Fix broken sync script for rsync v3.1.2
rsync v3.1.2 expects every line in the `--from-file` to have a newline.
Otherwise, it throws an error.  This cancels the entire sync.

```
* Running batch 2401-2700
  - Rsyncing metrics: rsync -azpS --copy-dest="/u2/carbon" --files-from /tmp/tmp1heicu_k carbon@1x.2x.3x.9x:/u2/carbon/ /tmp/1
0.20.36.96dz00hbdq/
ERROR: rejecting unrequested file-list name: whisper/diamond/xxxxxxx/xxxxxx/xxxxxx/memory/SwapFree.wsp
rsync error: protocol incompatibility (code 2) at flist.c(911) [Receiver=3.1.2]
WARNING:root:Failed to sync from carbon@1x.2x.3x.9x:/u2/carbon/! rsync rc=2
```